### ISSUE TITLE
yo not in path, how to use it - please make the readme more clear

### ISSUE THREAD

**Issue by cgrozea** [PlanQK/yo-generator-planqk-service#2]
after installing yo as in the readme, it is still not in path.
System:
ubuntu 18.04
npm version
{
  npm: '6.14.11',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '7',
  nghttp2: '1.41.0',
  node: '14.16.0',
  openssl: '1.1.1j',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.4.371.19-node.18',
  zlib: '1.2.11'
}

**Comment by cgrozea** [comment]
It landed in my case next to npm, this information could be useful

**Comment by miwurster** [comment]
Hi @cgrozea, this is strange. Did you use the global flag "-g" during installation? Further, have you tried to re-open you command-prompt after installation?

**Comment by miwurster** [comment]
Also, make sure that the `yo doctor` command successfully runs:

```
❯ yo doctor

Yeoman Doctor
Running sanity checks on your system

✔ No .bowerrc file in home directory
✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ No .yo-rc.json file in home directory
✔ Node.js version
✔ npm version
✔ yo version

Everything looks all right!
```

**Comment by cgrozea** [comment]
I think I did.
I had the npm in PATH just because I made a link from it to a directory in PATH.
The yo executable was in the same place as npm, which was not in my PATH without this link. I have linked yo too. It could well be something specific to my system - thus I propose you close this.
